# application dependencies
FROM python:3.11-slim as builder
WORKDIR /app
COPY requirements.txt .
RUN pip wheel --no-cache-dir --wheel-dir /app/wheels -r requirements.txt

# image
FROM python:3.11-slim
WORKDIR /app


COPY --from=builder /app/wheels /wheels
RUN pip install --no-cache-dir /wheels/*


COPY ./streamlit_app ./streamlit_app
COPY ./requirements.txt .

# Run 
CMD ["streamlit", "run", "streamlit_app/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
