name: CC-churn-prediction
services:
  fastapi:
    build:
      context: .
      dockerfile: dockerfile.fastapi
    container_name: fastapi_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    restart: always
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: dockerfile.streamlit
    container_name: streamlit_service
    command: streamlit run streamlit_app/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    restart: always
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


