# application dependencies
FROM python:3.11-slim as builder
WORKDIR /app
COPY requirements.txt .
RUN pip wheel --no-cache-dir --wheel-dir /app/wheels -r requirements.txt

# image
FROM python:3.11-slim
WORKDIR /app


COPY --from=builder /app/wheels /wheels
RUN pip install --no-cache-dir /wheels/*

COPY ./app ./app
COPY ./app/model/model.pkl ./app/model/model.pkl

# Run
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
